[package]
name = "sparse_vec"
description = "Compress vectors using row displacement"
version = "0.1.0"
authors = ["Lukas Diekmann <lukas.diekmann@gmail.com>"]
repository = "https://github.com/softdevteam/sparsevec/"
readme = "README.md"
# This should be "Apache-2.0 OR MIT OR UPL-1.0" but crates.io doesn't know about
# UPL-1.0.
license = "Apache-2.0 OR MIT"

[dependencies]
vob = { version="2.0", features=["serde"] }
packedvec = { git = "https://github.com/softdevteam/packedvec", features=["serde"] }
serde = { version="1.0", features=["derive"], optional=true }
num-traits = "0.2"
rand = "0.5"
